en:
  languageCode: en
  languageName: English
  # Uncomment for multilingual sites, and move the default content into corresponding sub-folder.
  contentDir: content/en
  copyright: CC BY-NC 4.0

de:
  languageCode: de
  languageName: Deutsch
  # Uncomment for multilingual sites, and move the default content into corresponding sub-folder.
  contentDir: content/de
  copyright: CC BY-NC 4.0

# Uncomment for multilingual sites, and customize the following config.
# zh:
#   languageCode: zh
#   languageName: 简体中文
#   contentDir: content/zh
#   title: 中文标题